# Generated by Django 4.0.5 on 2022-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skintype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skintype')),
            ],
            options={
                'db_table': 'users',
            },
            bases=('core.timestampmodel',),
        ),
    ]
