# Generated by Django 4.0.5 on 2022-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'features',
            },
            bases=('core.timestampmodel',),
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('name', models.CharField(max_length=50)),
                ('ontents', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
            bases=('core.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=50)),
                ('Main_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.maincategory')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('recommend_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_products', to='product.product')),
                ('reference_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_products', to='product.product')),
            ],
            options={
                'db_table': 'recommend_products',
            },
            bases=('core.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Productoption',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('sizes_mL', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_include_pump', models.BooleanField(default=False)),
                ('size_contents', models.TextField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_options',
            },
            bases=('core.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Productfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_feature', to='product.product')),
            ],
            options={
                'db_table': 'products_features',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
