# Generated by Django 4.0.5 on 2022-06-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ontents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Main_Category',
            new_name='main_Category',
        ),
    ]
