# Generated by Django 4.0.5 on 2022-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_category_category_main_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_show_all',
            field=models.BooleanField(default=False),
        ),
    ]
