# Generated by Django 4.0.5 on 2022-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_mainsub_mainsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
