# Generated by Django 4.0.5 on 2022-06-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='main_sub_category',
        ),
    ]
